/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.views;

import view.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import librarian.views.RegisterLibrarianForm;
import login.controller.LoginController;
import user.dao.MysqlAccountDao;
import user.view.ForgotPassForm;
import user.view.UserMainForm;
import util.Constants;

/**
 *
 * @author Linh
 */
public class LoginForm extends javax.swing.JFrame {
    
    int x = 0, y = 100;
    private LoginController loginController;
    private String typeLogin;

    /**
     * Creates new form LoginForm
     */
    public LoginForm(String typeLogin) {
        initComponents();
        setLocationRelativeTo(null);
        this.typeLogin = typeLogin;
        loginController = new LoginController();
        jLabelTitle.setForeground(Color.red);
        checkTypeLogin(typeLogin);
        t.start();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                (LoginForm.this).setVisible(false);
                new ChooseLoginForm().setVisible(true);
            }
        });
    }
    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            int x = 74, y = 21;
            try {
                while (x < 660) {
                    jLabelTitle.setLocation(x, y);
                    t.sleep(200);
                    x = x + 20;
                    if (x >= 660) {
                        x = 0;
                    }
                    
                }
            } catch (InterruptedException Ie) {
                System.out.println("mvpdemo.RegisterForm.runAnimation()" + Ie.getMessage());
            }
            
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        registerButon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tài khoản :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 156, 66, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Mật khẩu :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 187, 66, -1));
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 153, 151, -1));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 184, 151, -1));

        jLabel1.setText("<html><u>Quên mật khẩu?<u><html>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 23));

        loginButton.setText("Đăng nhập");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doLogin(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 239, -1, -1));

        registerButon.setText("Đăng ký");
        registerButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRegisterForm(evt);
            }
        });
        getContentPane().add(registerButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 239, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><u>Đăng nhập với tư cách là khách<u><html>");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginWithGuess(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 280, 190, 28));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Chào mừng quý độc giả đến với Thư Viện BK LKL");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 21, 512, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bg_library.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openRegisterForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRegisterForm
        // TODO add your handling code here:
        
        if (typeLogin.equals(Constants.LOGIN_WITH_USER)) {
            RegisterForm registerForm = new RegisterForm();
            registerForm.setVisible(true);
        } else if (typeLogin.equals(Constants.LOGIN_WITH_LIBRARIAN)) {
            RegisterLibrarianForm form = new RegisterLibrarianForm();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_openRegisterForm

    private void doLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doLogin
        // TODO add your handling code here:
        login(userNameField.getText(), Arrays.toString(passField.getPassword()));
        

    }//GEN-LAST:event_doLogin

    private void loginWithGuess(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginWithGuess
        // TODO add your handling code here:
        UserMainForm mainForm = new UserMainForm(null);
        mainForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginWithGuess

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ForgotPassForm forgotPassForm = new ForgotPassForm(typeLogin);
        forgotPassForm.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked
    private void login(String username, String pass) {
        if (username.isEmpty() || passField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải điền đầy đủ thông tin", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int loginType = loginController.checkLogin(username, pass, typeLogin);
                switch (loginType) {
                    case MysqlAccountDao.LOGIN_WITH_READER:
                        //TODO show HomeForm.
                        UserMainForm mainForm = new UserMainForm(username);
                        mainForm.setVisible(true);
                        this.setVisible(false);
                        break;
                    case MysqlAccountDao.LOGIN_WITH_LIBRARIAN:
                        ManagementForm managementForm = new ManagementForm(username);
                        managementForm.setVisible(true);
                        this.setVisible(false);
                        break;
                    
                    case MysqlAccountDao.LOGIN_WITH_ADMIN:
                        //TODO show admin form
                        break;
                    case MysqlAccountDao.LOGIN_FAIL_CONECTION:
                        JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình đăng nhập,Kiểm tra lại kết nối mạng", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        //TODO show admin form
                        break;
                    
                    case MysqlAccountDao.LOGIN_FAIL:
                        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        break;
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình đăng nhập,Vui lòng thử lại sau", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }
    
    private void checkTypeLogin(String typeLogin) {
        if (typeLogin.equalsIgnoreCase(Constants.LOGIN_WITH_LIBRARIAN)) {
            jLabel2.setVisible(false);
        } else if (typeLogin.equalsIgnoreCase(Constants.LOGIN_WITH_USER)) {
            jLabel2.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton registerButon;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
