/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.views;

import view.*;
import card.model.BorrowCard;
import com.mysql.cj.protocol.Message;
import java.util.Arrays;
import javax.swing.JOptionPane;
import login.views.LoginForm;
import user.Account;
import user.User;
import user.controller.UserController;
import user.dao.MysqlUserDao;
import util.Constants;
import util.HashPassword;

/**
 *
 * @author Linh
 */
public class RegisterForm extends javax.swing.JFrame {

    private UserController userController;

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        userController = new UserController();
        jPanel1.setOpaque(false);
        male.setActionCommand(Constants.SEX_MALE);
        female.setActionCommand(Constants.SEX_FEMALE);
        other.setActionCommand(Constants.SEX_OTHER);
        typeStudentUserRegis.setActionCommand(Constants.STUDENT);
        typeOtherUserRegis.setActionCommand(Constants.OTHER);
        t.start();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                RegisterForm.this.setVisible(false);
            }
        });
        //runAnimation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        sexGroup = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        idStudentField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        periodComboField = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        typeStudentUserRegis = new javax.swing.JRadioButton();
        typeOtherUserRegis = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        checkReadTerm = new javax.swing.JCheckBox();
        jLabelTitle = new javax.swing.JLabel();
        backLogin = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đăng ký"));

        jLabel1.setText("Tài khoản");

        jLabel2.setText("Họ và Tên");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Đối tượng");

        jLabel7.setText("Mã Sinh Viên");

        idStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idStudentFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Học kỳ");

        periodComboField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20151", "20152", "20153", "20161", "20162", "20163", "20171", "20172", "20173", "20181", "20182", "20183" }));

        jLabel10.setText("Email");

        jLabel11.setText("Điện thoại");

        jLabel12.setText("Giới tính");

        sexGroup.add(male);
        male.setSelected(true);
        male.setText("Nam");

        sexGroup.add(female);
        female.setText("Nữ");

        sexGroup.add(other);
        other.setText("khác");

        typeGroup.add(typeStudentUserRegis);
        typeStudentUserRegis.setSelected(true);
        typeStudentUserRegis.setText("Sinh Viên Hust");

        typeGroup.add(typeOtherUserRegis);
        typeOtherUserRegis.setText("Khác");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("*Tối thiếu 6 ký tự");

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*Số thẻ ngân hàng đối với đối tượng khác");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(male)
                .addGap(18, 18, 18)
                .addComponent(female)
                .addGap(18, 18, 18)
                .addComponent(other)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeStudentUserRegis)
                        .addGap(42, 42, 42)
                        .addComponent(typeOtherUserRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodComboField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nameField, passField, usernameField});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailField, idStudentField, phoneField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeOtherUserRegis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(typeStudentUserRegis)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(idStudentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(periodComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(other))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jButton1.setText("Gửi đăng ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkReadTerm.setText("Tôi đã đọc rõ nội quy của thư viện");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Thư viện BK LKL hân hạnh phục vụ quý khách");

        backLogin.setText("trở lại");
        backLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkReadTerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(checkReadTerm)
                    .addComponent(backLogin))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idStudentFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        switch (sendRegisteUser()) {
            case MysqlUserDao.RESULT_NULL_POINT:
                JOptionPane.showMessageDialog(this, "Bạn cần điền đầy đủ các trường");
                break;
            case MysqlUserDao.RESULT_EMAIL_INCORRECT:
                JOptionPane.showMessageDialog(this, "Email không hợp lệ");
                break;
            case MysqlUserDao.RESULT_PHONE_INCORRECT:
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
                break;
            case MysqlUserDao.RESULT_PASS_SMALL:
                JOptionPane.showMessageDialog(this, "Mật khẩu quá ngắn");
                break;
            case MysqlUserDao.RESULT_ID_EXITS:
                JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
                break;
            case MysqlUserDao.RESULT_NO_CHECK_TERM:
                JOptionPane.showMessageDialog(this, "Bạn cần tích đọc rõ nội quy");
                break;
            case MysqlUserDao.RESULT_SUCCESS:
                resetField();
                JOptionPane.showMessageDialog(this, "Gửi đăng ký thành công,bạn phải chờ kích hoạt thẻ để có thể mượn sách");
                break;
            case MysqlUserDao.RESULT_SQLITE:
                JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra, mời đăng ký lại sau", "Thông báo", JOptionPane.ERROR_MESSAGE);
                break;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void backLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backLoginActionPerformed
    public int sendRegisteUser() {
        boolean check = checkReadTerm.isSelected();
        String id = usernameField.getText().trim();
        String name = nameField.getText().trim();
        String sex = sexGroup.getSelection().getActionCommand();
        String phone = phoneField.getText().trim();
        String type = typeGroup.getSelection().getActionCommand();
        String period = null;
        //  String id, String name, String studentId, String sex, String period, String email, String phone, String pass
        if (type.equals(Constants.STUDENT)) {
            period = periodComboField.getSelectedItem().toString();
        }
        String email = emailField.getText().trim();
        String studentId = idStudentField.getText().trim();

        return userController.insertUser(check, id, name, studentId, sex, period, email, phone, passField.getPassword());

    }

    private void resetField() {
        usernameField.setText("");
        nameField.setText("");
        passField.setText("");
        phoneField.setText("");
        emailField.setText("");
        idStudentField.setText("");
    }
    /**
     * @param args the command line arguments
     */

    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            int x = 90, y = 0;
            try {
                while (x < 521) {
                    jLabelTitle.setLocation(x, y);
                    t.sleep(200);
                    x = x + 20;
                    if (x > 521) {
                        x = 0;
                    }

                }
            } catch (InterruptedException Ie) {
                System.out.println("mvpdemo.RegisterForm.runAnimation()" + Ie.getMessage());
            }

        }
    });

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLogin;
    private javax.swing.JCheckBox checkReadTerm;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField idStudentField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton other;
    private javax.swing.JPasswordField passField;
    private javax.swing.JComboBox<String> periodComboField;
    private javax.swing.JTextField phoneField;
    private javax.swing.ButtonGroup sexGroup;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JRadioButton typeOtherUserRegis;
    private javax.swing.JRadioButton typeStudentUserRegis;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
