/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book.views;

import book.controller.BookController;
import book.dao.MysqlBookDao;
import book.model.Book;
import view.*;
import bookcopy.controller.BookCopyController;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_EXCEPTION_PRICE;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_NULL_POINT;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_SQLITE;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_SUCCESS;
import bookcopy.model.BookCopy;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import librarian.controller.LibrarianController;
import librarian.model.Librarian;
import login.views.ChooseLoginForm;
import user.dao.MysqlAccountDao;
import user.view.InforBookForm;
import util.Constants;

/**
 *
 * @author Linh
 */
public class ManagerBookForm extends javax.swing.JFrame {

    BookCopyController controller;
    LibrarianController lc;
    private DefaultTableModel modelAddbookCopyPanel;
    private DefaultTableModel modelInforBookPanel;
    private String idLib;
    BookController bc;
    BookCopyController bcc;

    /**
     * Creates new form ManagerBookForm
     */
    public ManagerBookForm(String idLib) {
        initComponents();
        setLocationRelativeTo(null);
        this.idLib = idLib;
        borrowableRadioField.setSelected(true);
        borrowableRadioField.setActionCommand(Constants.TYPE_BORROWABLE);
        referenceField.setActionCommand(Constants.TYPE_REFERENCES);
        controller = new BookCopyController();
        bc = new BookController();
        lc = new LibrarianController();
        bcc = new BookCopyController();
        modelAddbookCopyPanel = (DefaultTableModel) tableBookCopyForm.getModel();
        modelInforBookPanel = (DefaultTableModel) tableInforBook.getModel();
        controller.displayListCategory(cateAddBookFormCb);
        controller.displayListCategoryForSearch(categoryCbField);
        controller.displayListPublisher(pubAddBookFormCb);
        controller.displayListPublisherForSearch(pubCbboxField);
        List<Book> listBooks = bc.getAllBook();
        if (listBooks != null) {
            bc.displayBookListToTable(tableAddBookForm, listBooks);
            controller.displayListBook(modelInforBookPanel, listBooks);
            controller.displayListBook(modelAddbookCopyPanel, listBooks);
        }
        setVisiableInforBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        groupTyoeBookCopiesField = new javax.swing.ButtonGroup();
        jPopupMenu_managerBook = new javax.swing.JPopupMenu();
        jMenuItem_deleteBook = new javax.swing.JMenuItem();
        jMenuItem_updateBook = new javax.swing.JMenuItem();
        jMenuItem_inforBookCopy = new javax.swing.JMenuItem();
        jDialog_updateBook = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_idBookUpdate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_nameBookUpdate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_authorBookUpdate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton_updateBook = new javax.swing.JButton();
        jComboBox_publisherBookUpdate = new javax.swing.JComboBox<>();
        jComboBox_categoryBookUpdate = new javax.swing.JComboBox<>();
        jDialog_changePassLib = new javax.swing.JDialog();
        jPanel_changePass = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField_PassOld = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPasswordField_PassNew = new javax.swing.JPasswordField();
        jPasswordField_PassAgain = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel_inforBook = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idBookField = new javax.swing.JTextField();
        nameBookField = new javax.swing.JTextField();
        pubCbboxField = new javax.swing.JComboBox<>();
        categoryCbField = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        authorBookField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInforBook = new javax.swing.JTable();
        jPanel_addBook = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        titleAddBookFormField = new javax.swing.JTextField();
        authorAddBookFormField = new javax.swing.JTextField();
        pubAddBookFormCb = new javax.swing.JComboBox<>();
        cateAddBookFormCb = new javax.swing.JComboBox<>();
        addBookButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAddBookForm = new javax.swing.JTable();
        jPanel_addBookCopy = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        referenceField = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        numberCopyField = new javax.swing.JSpinner();
        priceCopiesField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        titleBookCopyFormField = new javax.swing.JTextField();
        addCopiesButton = new javax.swing.JButton();
        idBookAddCopyFormField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        authorBookCopyFormField = new javax.swing.JTextField();
        pubAddCopyFormField = new javax.swing.JTextField();
        catAddCopyFormField = new javax.swing.JTextField();
        borrowableRadioField = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBookCopyForm = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_changePassLib = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_inforBook = new javax.swing.JMenuItem();
        jMenuItem_addBook = new javax.swing.JMenuItem();
        jMenuItem_addBookCopy = new javax.swing.JMenuItem();

        jMenuItem_deleteBook.setText("Xóa");
        jMenuItem_deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_deleteBookActionPerformed(evt);
            }
        });
        jPopupMenu_managerBook.add(jMenuItem_deleteBook);

        jMenuItem_updateBook.setText("Cập nhật");
        jMenuItem_updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_updateBookActionPerformed(evt);
            }
        });
        jPopupMenu_managerBook.add(jMenuItem_updateBook);

        jMenuItem_inforBookCopy.setText("Thông tin bản copy");
        jMenuItem_inforBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inforBookCopyActionPerformed(evt);
            }
        });
        jPopupMenu_managerBook.add(jMenuItem_inforBookCopy);

        jDialog_updateBook.setTitle("Cập nhật thông tin sách");

        jLabel5.setText("Nhập thông tin cần thay đổi dưới đây");

        jLabel16.setText("Mã sách : ");

        jTextField_idBookUpdate.setEditable(false);

        jLabel19.setText("Tên sách :");

        jLabel20.setText("Tác giả :");

        jLabel21.setText("Nhà xuất bản :");

        jLabel22.setText("Thể loại :");

        jButton_updateBook.setText("Cập nhật");
        jButton_updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_updateBookLayout = new javax.swing.GroupLayout(jDialog_updateBook.getContentPane());
        jDialog_updateBook.getContentPane().setLayout(jDialog_updateBookLayout);
        jDialog_updateBookLayout.setHorizontalGroup(
            jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_updateBookLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_idBookUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextField_nameBookUpdate)
                            .addComponent(jTextField_authorBookUpdate, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jComboBox_publisherBookUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_categoryBookUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_updateBook)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialog_updateBookLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox_categoryBookUpdate, jComboBox_publisherBookUpdate, jTextField_authorBookUpdate, jTextField_idBookUpdate, jTextField_nameBookUpdate});

        jDialog_updateBookLayout.setVerticalGroup(
            jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_idBookUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_nameBookUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_authorBookUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox_publisherBookUpdate))
                    .addGroup(jDialog_updateBookLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addGroup(jDialog_updateBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_categoryBookUpdate))
                .addGap(18, 18, 18)
                .addComponent(jButton_updateBook, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog_updateBookLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_categoryBookUpdate, jComboBox_publisherBookUpdate, jTextField_authorBookUpdate, jTextField_idBookUpdate, jTextField_nameBookUpdate});

        jDialog_changePassLib.setTitle("Thay đổi mật khẩu");

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(234, 19, 89));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Bạn vui lòng điền mật khẩu mới vào ô dưới đây");

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(239, 34, 127));
        jLabel30.setText("Mật khẩu cũ :");

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(239, 34, 127));
        jLabel31.setText("Mật khẩu mới :");

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(239, 34, 127));
        jLabel32.setText("Nhập lại :");

        jButton3.setText("Đổi mật khẩu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_changePassLayout = new javax.swing.GroupLayout(jPanel_changePass);
        jPanel_changePass.setLayout(jPanel_changePassLayout);
        jPanel_changePassLayout.setHorizontalGroup(
            jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_changePassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_changePassLayout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_changePassLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField_PassNew)
                            .addComponent(jPasswordField_PassOld)
                            .addComponent(jPasswordField_PassAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
            .addGroup(jPanel_changePassLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_changePassLayout.setVerticalGroup(
            jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_changePassLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_PassOld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jPasswordField_PassNew))
                .addGap(18, 18, 18)
                .addGroup(jPanel_changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_PassAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_changePassLibLayout = new javax.swing.GroupLayout(jDialog_changePassLib.getContentPane());
        jDialog_changePassLib.getContentPane().setLayout(jDialog_changePassLibLayout);
        jDialog_changePassLibLayout.setHorizontalGroup(
            jDialog_changePassLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(jDialog_changePassLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_changePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_changePassLibLayout.setVerticalGroup(
            jDialog_changePassLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(jDialog_changePassLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_changePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang quản lý sách");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sách"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã sách");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nhà xuất bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Thể loại");

        jLabel24.setText("Tác giả");

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idBookField)
                                .addComponent(nameBookField)
                                .addComponent(authorBookField)
                                .addComponent(categoryCbField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pubCbboxField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(200, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idBookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameBookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(authorBookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pubCbboxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoryCbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tableInforBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Thể loại", "Số lượng bản copy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPopupMenu_managerBook, org.jdesktop.beansbinding.ObjectProperty.create(), tableInforBook, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tableInforBook);

        javax.swing.GroupLayout jPanel_inforBookLayout = new javax.swing.GroupLayout(jPanel_inforBook);
        jPanel_inforBook.setLayout(jPanel_inforBookLayout);
        jPanel_inforBookLayout.setHorizontalGroup(
            jPanel_inforBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inforBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inforBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_inforBookLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 316, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_inforBookLayout.setVerticalGroup(
            jPanel_inforBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inforBookLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Điền thông tin sách"));

        jLabel12.setText("Tên sách");

        jLabel13.setText("Tác giả");

        jLabel14.setText("Nhà xuất bản");

        jLabel15.setText("Thể loại");

        addBookButton.setText("Thêm");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))))
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titleAddBookFormField)
                        .addComponent(authorAddBookFormField)
                        .addComponent(pubAddBookFormCb, 0, 229, Short.MAX_VALUE)
                        .addComponent(cateAddBookFormCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleAddBookFormField))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(authorAddBookFormField)))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubAddBookFormCb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cateAddBookFormCb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15});

        tableAddBookForm.setAutoCreateRowSorter(true);
        tableAddBookForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableAddBookForm);

        javax.swing.GroupLayout jPanel_addBookLayout = new javax.swing.GroupLayout(jPanel_addBook);
        jPanel_addBook.setLayout(jPanel_addBookLayout);
        jPanel_addBookLayout.setHorizontalGroup(
            jPanel_addBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_addBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_addBookLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 349, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel_addBookLayout.setVerticalGroup(
            jPanel_addBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );

        jPanel_addBookCopy.setPreferredSize(new java.awt.Dimension(882, 561));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Điền thông tin"));

        jLabel6.setText("Mã sách");

        jLabel7.setText("Số lượng ");

        jLabel8.setText("Loại sách");

        groupTyoeBookCopiesField.add(referenceField);
        referenceField.setText("Tham khảo");
        referenceField.setActionCommand("Có thể mượn");

        jLabel9.setText("Giá bản Copy");

        numberCopyField.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel10.setText("Tên sách");

        jLabel17.setText("Nhà xuất bản");

        jLabel18.setText("Thể loại");

        titleBookCopyFormField.setEditable(false);

        addCopiesButton.setText("Thêm bản copies");
        addCopiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCopiesButtonClick(evt);
            }
        });

        idBookAddCopyFormField.setEditable(false);

        jLabel25.setText("Tác giả");

        authorBookCopyFormField.setEditable(false);

        pubAddCopyFormField.setEditable(false);

        catAddCopyFormField.setEditable(false);

        groupTyoeBookCopiesField.add(borrowableRadioField);
        borrowableRadioField.setText("Có thể mượn");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberCopyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(borrowableRadioField)
                        .addGap(22, 22, 22)
                        .addComponent(referenceField))
                    .addComponent(idBookAddCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleBookCopyFormField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(authorBookCopyFormField)
                    .addComponent(pubAddCopyFormField)
                    .addComponent(catAddCopyFormField))
                .addGap(42, 42, 42))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(addCopiesButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel17, jLabel18, jLabel25, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(titleBookCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idBookAddCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(numberCopyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(authorBookCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(referenceField)
                            .addComponent(borrowableRadioField))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(priceCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(pubAddCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(catAddCopyFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(addCopiesButton)
                .addContainerGap())
        );

        tableBookCopyForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Thể loại ", "Số lượng bản copy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBookCopyForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookCopyFormMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBookCopyForm);

        javax.swing.GroupLayout jPanel_addBookCopyLayout = new javax.swing.GroupLayout(jPanel_addBookCopy);
        jPanel_addBookCopy.setLayout(jPanel_addBookCopyLayout);
        jPanel_addBookCopyLayout.setHorizontalGroup(
            jPanel_addBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addBookCopyLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel_addBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_addBookCopyLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel_addBookCopyLayout.setVerticalGroup(
            jPanel_addBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addBookCopyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel_inforBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_addBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_addBookCopy, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_inforBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_addBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_addBookCopy, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_inforBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_addBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_addBookCopy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/applications_system.png"))); // NOI18N
        jMenu1.setText("Hệ thống");

        jMenuItem_changePassLib.setText("Đổi mật khẩu");
        jMenuItem_changePassLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_changePassLibActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_changePassLib);

        jMenuItem1.setText("Trở về màn hình chức năng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Thoát");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/utilitie.png"))); // NOI18N
        jMenu2.setText("Tính năng");

        jMenuItem_inforBook.setText("Thông tin và cập nhật sách");
        jMenuItem_inforBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inforBookActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_inforBook);

        jMenuItem_addBook.setText("Thêm sách");
        jMenuItem_addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addBookActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_addBook);

        jMenuItem_addBookCopy.setText("Thêm sách copy");
        jMenuItem_addBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addBookCopyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_addBookCopy);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetText() {
        idBookAddCopyFormField.setText("");
        titleBookCopyFormField.setText("");
        authorBookCopyFormField.setText("");
        pubAddCopyFormField.setText("");
        catAddCopyFormField.setText("");
        priceCopiesField.setText("");
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ManagementForm(idLib).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChooseLoginForm chooseLoginForm = new ChooseLoginForm();
        chooseLoginForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tableBookCopyFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookCopyFormMouseClicked
        // TODO add your handling code here:
        int row = tableBookCopyForm.getSelectedRow();
        if (row >= 0) {
            idBookAddCopyFormField.setText(tableBookCopyForm.getValueAt(row, 0).toString());
            titleBookCopyFormField.setText(tableBookCopyForm.getValueAt(row, 1).toString());
            authorBookCopyFormField.setText(tableBookCopyForm.getValueAt(row, 2).toString());
            pubAddCopyFormField.setText(tableBookCopyForm.getValueAt(row, 3).toString());
            catAddCopyFormField.setText(tableBookCopyForm.getValueAt(row, 4).toString());

        }
    }//GEN-LAST:event_tableBookCopyFormMouseClicked

    private void addCopiesButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCopiesButtonClick
        // TODO add your handling code here:
        String id = idBookAddCopyFormField.getText();
        String price = priceCopiesField.getText();
        String type = groupTyoeBookCopiesField.getSelection().getActionCommand();
        int count = (int) numberCopyField.getValue();
        int result = controller.addBookCopies(id, count, price, type);
        switch (result) {
            case RESULT_NULL_POINT:
                JOptionPane.showMessageDialog(this, "Bạn phải Điền đầy đủ thông tin");
                break;
            case RESULT_EXCEPTION_PRICE:
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giá tiền hợp lệ!");
                break;
            case RESULT_SUCCESS:
                int countCopy = (int) tableBookCopyForm.getValueAt(tableBookCopyForm.getSelectedRow(), 5);
                tableBookCopyForm.setValueAt(countCopy + count, tableBookCopyForm.getSelectedRow(), 5);
                resetText();
                controller.updateCountBookCopy(tableInforBook, id, count);
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                break;
            case RESULT_SQLITE:
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình thêm!");
                break;
        }
    }//GEN-LAST:event_addCopiesButtonClick

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // TODO add your handling code here:
        addBook();
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void jMenuItem_inforBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inforBookActionPerformed
        // TODO add your handling code here:
        setVisiableInforBook();
    }//GEN-LAST:event_jMenuItem_inforBookActionPerformed

    private void jMenuItem_addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addBookActionPerformed
        // TODO add your handling code here:
        setVisiableAddBook();
    }//GEN-LAST:event_jMenuItem_addBookActionPerformed

    private void jMenuItem_addBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addBookCopyActionPerformed
        setVisiableAddBookCopy();
    }//GEN-LAST:event_jMenuItem_addBookCopyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        searchBook();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem_updateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_updateBookActionPerformed
        // TODO add your handling code here:
        int index = tableInforBook.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cập nhật.Vui lòng chọn lại!!!");
        } else {
            setVisiableDiaglogUpdateBook(index);
        }
    }//GEN-LAST:event_jMenuItem_updateBookActionPerformed

    private void jButton_updateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateBookActionPerformed
        // TODO add your handling code here:
        updateInforBook();
    }//GEN-LAST:event_jButton_updateBookActionPerformed

    private void jMenuItem_deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_deleteBookActionPerformed
        // TODO add your handling code here:
        int index = tableInforBook.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách cần xóa.Vui lòng chọn lại!!!");
        } else {

        }
    }//GEN-LAST:event_jMenuItem_deleteBookActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        changePassLib();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem_changePassLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_changePassLibActionPerformed
        // TODO add your handling code here:
        jDialog_changePassLib.setVisible(true);
        jDialog_changePassLib.setSize(500, 400);
        jDialog_changePassLib.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem_changePassLibActionPerformed

    private void jMenuItem_inforBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inforBookCopyActionPerformed
        // TODO add your handling code here:
        displayInforBook();
    }//GEN-LAST:event_jMenuItem_inforBookCopyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addCopiesButton;
    private javax.swing.JTextField authorAddBookFormField;
    private javax.swing.JTextField authorBookCopyFormField;
    private javax.swing.JTextField authorBookField;
    private javax.swing.JRadioButton borrowableRadioField;
    private javax.swing.JTextField catAddCopyFormField;
    private javax.swing.JComboBox<String> cateAddBookFormCb;
    private javax.swing.JComboBox<String> categoryCbField;
    private javax.swing.ButtonGroup groupTyoeBookCopiesField;
    private javax.swing.JTextField idBookAddCopyFormField;
    private javax.swing.JTextField idBookField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_updateBook;
    private javax.swing.JComboBox<String> jComboBox_categoryBookUpdate;
    private javax.swing.JComboBox<String> jComboBox_publisherBookUpdate;
    private javax.swing.JDialog jDialog_changePassLib;
    private javax.swing.JDialog jDialog_updateBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_addBook;
    private javax.swing.JMenuItem jMenuItem_addBookCopy;
    private javax.swing.JMenuItem jMenuItem_changePassLib;
    private javax.swing.JMenuItem jMenuItem_deleteBook;
    private javax.swing.JMenuItem jMenuItem_inforBook;
    private javax.swing.JMenuItem jMenuItem_inforBookCopy;
    private javax.swing.JMenuItem jMenuItem_updateBook;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_addBook;
    private javax.swing.JPanel jPanel_addBookCopy;
    private javax.swing.JPanel jPanel_changePass;
    private javax.swing.JPanel jPanel_inforBook;
    private javax.swing.JPasswordField jPasswordField_PassAgain;
    private javax.swing.JPasswordField jPasswordField_PassNew;
    private javax.swing.JPasswordField jPasswordField_PassOld;
    private javax.swing.JPopupMenu jPopupMenu_managerBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_authorBookUpdate;
    private javax.swing.JTextField jTextField_idBookUpdate;
    private javax.swing.JTextField jTextField_nameBookUpdate;
    private javax.swing.JTextField nameBookField;
    private javax.swing.JSpinner numberCopyField;
    private javax.swing.JTextField priceCopiesField;
    private javax.swing.JComboBox<String> pubAddBookFormCb;
    private javax.swing.JTextField pubAddCopyFormField;
    private javax.swing.JComboBox<String> pubCbboxField;
    private javax.swing.JRadioButton referenceField;
    private javax.swing.JTable tableAddBookForm;
    private javax.swing.JTable tableBookCopyForm;
    private javax.swing.JTable tableInforBook;
    private javax.swing.JTextField titleAddBookFormField;
    private javax.swing.JTextField titleBookCopyFormField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void addBook() {
        String title = titleAddBookFormField.getText();
        String author = authorAddBookFormField.getText();
        String publisher = pubAddBookFormCb.getSelectedItem().toString();
        String category = cateAddBookFormCb.getSelectedItem().toString();
        int result = bc.addBook(title, author, publisher, category);
        switch (result) {
            case MysqlBookDao.RESULT_NULL_POINT:
                JOptionPane.showMessageDialog(this, "Các trường dữ liệu không được để trống");
                break;
            case MysqlBookDao.BOOK_ADD_SAME:
                JOptionPane.showMessageDialog(this, "Sách bạn thêm đã có.Vui lòng chọn chức năng thêm sách copy");
                break;
            case MysqlBookDao.RESULT_SQLITE:
                JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra.Vui lòng thử lại sau");
                break;
            case MysqlBookDao.RESULT_SUCCESS:
                JOptionPane.showMessageDialog(this, "Thêm sách thành công");
//                bc.addBookToTable(tableAddBookForm, book);
//                controller.addBookToTable(modelInforBookPanel, book);
//                controller.addBookToTable(modelAddbookCopyPanel, book);
                break;
        }
    }

    private void setVisiableInforBook() {
        jPanel_inforBook.setVisible(true);
        jPanel_addBook.setVisible(false);
        jPanel_addBookCopy.setVisible(false);
    }

    private void setVisiableAddBook() {
        jPanel_inforBook.setVisible(false);
        jPanel_addBook.setVisible(true);
        jPanel_addBookCopy.setVisible(false);
    }

    private void setVisiableAddBookCopy() {
        jPanel_inforBook.setVisible(false);
        jPanel_addBook.setVisible(false);
        jPanel_addBookCopy.setVisible(true);
    }

    private void searchBook() {
        String idSearch = idBookField.getText();
        String titleSearch = nameBookField.getText();
        String authorSearch = authorBookField.getText();
        String publishSearch = "";
        if (pubCbboxField.getSelectedItem() != null) {
            publishSearch = pubCbboxField.getSelectedItem().toString();
        };
        String categorySearch = "";
        if (categoryCbField.getSelectedItem() != null) {
            categorySearch = categoryCbField.getSelectedItem().toString();
        }
        bc.displayBookListToTable(tableInforBook, bc.searchBook_Manager(idSearch, titleSearch, authorSearch, publishSearch, categorySearch));
    }

    private void setVisiableDiaglogUpdateBook(int index) {
        jDialog_updateBook.setVisible(true);
        jDialog_updateBook.setSize(400, 380);
        jDialog_updateBook.setLocationRelativeTo(null);
        jTextField_idBookUpdate.setText(tableInforBook.getValueAt(index, 0).toString());
        jTextField_nameBookUpdate.setText(tableInforBook.getValueAt(index, 1).toString());
        jTextField_authorBookUpdate.setText(tableInforBook.getValueAt(index, 2).toString());
        jComboBox_categoryBookUpdate.removeAllItems();
        jComboBox_categoryBookUpdate.addItem(tableInforBook.getValueAt(index, 4).toString());
        controller.displayListPublisher(jComboBox_publisherBookUpdate);
        jComboBox_publisherBookUpdate.setSelectedItem(tableInforBook.getValueAt(index, 3));
    }

    private void updateInforBook() {
        if (JOptionPane.showConfirmDialog(null, "Bạn có cập nhật thông tin cho sách này không ??", "Thông báo ",
                JOptionPane.YES_OPTION) == JOptionPane.YES_NO_OPTION) {
            String id = jTextField_idBookUpdate.getText();
            String title = jTextField_nameBookUpdate.getText();
            String author = jTextField_authorBookUpdate.getText();
            String pub = jComboBox_publisherBookUpdate.getSelectedItem().toString();
            String cat = jComboBox_categoryBookUpdate.getSelectedItem().toString();
            int result = bc.updateInforBook(id, title, author, pub, cat);
            switch (result) {
                case MysqlBookDao.RESULT_NULL_POINT:
                    JOptionPane.showMessageDialog(this, "Các trường dữ liệu không được để trống");
                    break;
                case MysqlBookDao.BOOK_ADD_SAME:
                    JOptionPane.showMessageDialog(this, "Sách bạn cập nhật đã có.Không thể sửa.Vui lòng xem lại hoặc chọn chức năng thêm bản copy");
                    break;
                case MysqlBookDao.RESULT_SQLITE:
                    JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra.Vui lòng thử lại sau");
                    break;
                case MysqlBookDao.RESULT_SUCCESS:
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin sách thành công");
                    bc.displayBookListToTable(tableInforBook, bc.getAllBook());
                    controller.updateInforBookCopy(tableBookCopyForm, id, title, author, pub);
                    jDialog_updateBook.setVisible(false);
                    break;
            }
        }
    }

    private void changePassLib() {
        String passOld = Arrays.toString(jPasswordField_PassOld.getPassword());
        String passNew = Arrays.toString(jPasswordField_PassNew.getPassword());
        String passAgain = Arrays.toString(jPasswordField_PassAgain.getPassword());
        if (jPasswordField_PassOld.getPassword().length == 0
                || jPasswordField_PassNew.getPassword().length == 0
                || jPasswordField_PassAgain.getPassword().length == 0) {
            JOptionPane.showMessageDialog(jDialog_changePassLib, "Bạn phải điền đầy đủ thông tin", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Librarian acc = new Librarian(idLib, passOld);
            int type = lc.changePassLib(acc, passNew, passAgain);
            switch (type) {
                case MysqlAccountDao.ACCOUNT_FALSE:
                    JOptionPane.showMessageDialog(jDialog_changePassLib, "Mật khẩu không chính xác.Vui lòng thử lại!!");
                    break;
                case MysqlAccountDao.PASSAGAIN_NOT_SAME_PASSNEW:
                    JOptionPane.showMessageDialog(jDialog_changePassLib, "Mật khẩu nhập lại không khớp.Vui lòng nhập lại!!");
                    break;
                case MysqlAccountDao.CHANGE_PASS_SUCCESS:
                    JOptionPane.showMessageDialog(jDialog_changePassLib, "Thay đổi mật khẩu thành công!!");
                    break;
                case MysqlAccountDao.FAILE_SYSTEM:
                    JOptionPane.showMessageDialog(jDialog_changePassLib, "Đã có lỗi xảy ra.Vui lòng thử lại!!");
                    break;

            }
        }
    }

    private void displayInforBook() {
        int index = tableInforBook.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách cần xem thông tin");
        } else {
            String idBook = tableInforBook.getValueAt(index, 0).toString();
            List<BookCopy> listBookCopy = bcc.getAllBookCopyById(idBook);
            InforBookForm inforBookForm = new InforBookForm();
            bcc.loadBookCopyToTable(inforBookForm.getjTable_inforBookCopy(), listBookCopy);
            inforBookForm.getjLabel_numberBookCopy().setText(listBookCopy.size() + "");
        }
    }
}
