/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.view;

import bookcopy.controller.BookCopyController;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_EXCEPTION_PRICE;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_EXCEPTION_STATUS;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_SQLITE;
import static bookcopy.dao.MysqlBookCopyDao.RESULT_SUCCESS;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kienanh2903
 */
public class InforBookForm extends javax.swing.JFrame {
    private BookCopyController bcc;
    /**
     * Creates new form InforBookForm
     */
    public InforBookForm() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        bcc = new BookCopyController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_updateBookCopy = new javax.swing.JPopupMenu();
        jMenuItem_updateBookCopy = new javax.swing.JMenuItem();
        jDialog_inforBookCopy = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField_idBookCopy = new javax.swing.JTextField();
        jTextField_status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_type = new javax.swing.JComboBox<>();
        SpinnerModel model = new SpinnerNumberModel(50000,0,50000000,10000);
        jSpinner_price = new javax.swing.JSpinner(model);
        jButton_updateInforBookCopy = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_numberBookCopy = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_inforBookCopy = new javax.swing.JTable();

        jMenuItem_updateBookCopy.setText("Cập nhật thông tin sách copy");
        jMenuItem_updateBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_updateBookCopyActionPerformed(evt);
            }
        });
        jPopupMenu_updateBookCopy.add(jMenuItem_updateBookCopy);

        jDialog_inforBookCopy.setTitle("Cập nhật thông tin sách copy");

        jLabel1.setText("Mã sách copy :");

        jTextField_idBookCopy.setEditable(false);

        jTextField_status.setEditable(false);

        jLabel2.setText("Tình trạng :");

        jLabel3.setText("Loại :");

        jLabel4.setText("Giá :");

        jComboBox_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tham khảo", "Có thể mượn" }));

        jButton_updateInforBookCopy.setText("Cập nhật");
        jButton_updateInforBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateInforBookCopyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_inforBookCopyLayout = new javax.swing.GroupLayout(jDialog_inforBookCopy.getContentPane());
        jDialog_inforBookCopy.getContentPane().setLayout(jDialog_inforBookCopyLayout);
        jDialog_inforBookCopyLayout.setHorizontalGroup(
            jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_inforBookCopyLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_inforBookCopyLayout.createSequentialGroup()
                        .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jTextField_idBookCopy, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_type, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                                .addComponent(jSpinner_price)))
                        .addGap(80, 80, 80))
                    .addGroup(jDialog_inforBookCopyLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton_updateInforBookCopy)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDialog_inforBookCopyLayout.setVerticalGroup(
            jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_inforBookCopyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_idBookCopy, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_status, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialog_inforBookCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton_updateInforBookCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin chi tiết các bản copy");

        jLabel9.setText("Tổng số bản copy :");

        jTable_inforBookCopy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách copy", "Tình trạng", "Loại sách", "Giá"
            }
        ));
        jTable_inforBookCopy.setComponentPopupMenu(jPopupMenu_updateBookCopy);
        jScrollPane4.setViewportView(jTable_inforBookCopy);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_numberBookCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_numberBookCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_updateBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_updateBookCopyActionPerformed
        // TODO add your handling code here:
        displayInforBookCopy();
    }//GEN-LAST:event_jMenuItem_updateBookCopyActionPerformed

    private void jButton_updateInforBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateInforBookCopyActionPerformed
        // TODO add your handling code here:
        updateInforBookCopy();
    }//GEN-LAST:event_jButton_updateInforBookCopyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InforBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InforBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InforBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InforBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InforBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_updateInforBookCopy;
    private javax.swing.JComboBox<String> jComboBox_type;
    private javax.swing.JDialog jDialog_inforBookCopy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_numberBookCopy;
    private javax.swing.JMenuItem jMenuItem_updateBookCopy;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu_updateBookCopy;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner_price;
    private javax.swing.JTable jTable_inforBookCopy;
    private javax.swing.JTextField jTextField_idBookCopy;
    private javax.swing.JTextField jTextField_status;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel_numberBookCopy() {
        return jLabel_numberBookCopy;
    }

    public JTable getjTable_inforBookCopy() {
        return jTable_inforBookCopy;
    }
    
    public void removeUpdateBookCopyPopupMenu(){
        jPopupMenu_updateBookCopy.remove(jMenuItem_updateBookCopy);
        jTable_inforBookCopy.remove(jPopupMenu_updateBookCopy);
    }

    private void displayInforBookCopy() {
        int index = jTable_inforBookCopy.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách cần cập nhật.Vui lòng chọn lại");
        }else{
            jDialog_inforBookCopy.setVisible(true);
            jDialog_inforBookCopy.setSize(400, 300);
            jDialog_inforBookCopy.setLocationRelativeTo(null);
            jTextField_idBookCopy.setText(jTable_inforBookCopy.getValueAt(index, 0).toString());
            jTextField_status.setText(jTable_inforBookCopy.getValueAt(index, 1).toString());
            jComboBox_type.setSelectedItem(jTable_inforBookCopy.getValueAt(index, 2).toString());
            jSpinner_price.setValue(Double.valueOf(jTable_inforBookCopy.getValueAt(index, 3).toString()));
        }
    }

    private void updateInforBookCopy() {
        int index =jTable_inforBookCopy.getSelectedRow();
        String typeOld = jTable_inforBookCopy.getValueAt(index, 2).toString();
        System.out.println(typeOld);
        String idCopy = jTextField_idBookCopy.getText();
        String status = jTextField_status.getText();
        String typeNew = jComboBox_type.getSelectedItem().toString();
        Double price = Double.parseDouble(jSpinner_price.getValue().toString());
        int resul = bcc.updateInforBookCopy(idCopy, status,typeOld, typeNew, price);
        switch(resul){
            case RESULT_EXCEPTION_STATUS :
                JOptionPane.showMessageDialog(this, "Sách này hiện đã được đăng ký hoặc cho mượn không thể sửa thành loại sách tham khảo.\nVui lòng thử lại sau");
                break;
            case RESULT_EXCEPTION_PRICE :
                JOptionPane.showMessageDialog(this, "Giá tiền không đúng.Vui lòng nhập lại");
                break;
            case RESULT_SQLITE :
                JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra.Vui lòng thử lại sau");
                break;
            case RESULT_SUCCESS :
                updateInfotBookCopyInTable(index, typeNew, price);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                break;
        }
    }
    private void updateInfotBookCopyInTable(int index, String typeNew, Double price){
        DefaultTableModel dtm = (DefaultTableModel) jTable_inforBookCopy.getModel();
        dtm.setValueAt(typeNew, index, 2);
        dtm.setValueAt(price, index, 3);
        jTable_inforBookCopy.setModel(dtm);
    }
}
